import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  var posts = [
    // { id: 1, title: "episode1", desc: "descriptidon1" },
    // { id: 2, title: "episode2", desc: "description2" },
    // { id: 3, title: "episode3", desc: "description3" },
    // { id: 4, title: "episode4", desc: "description4" },
  ];

  const [postTitle, setPosttitle] = useState();
  const [postDesc, setPostDesc] = useState();
  const handleChange = (event) => setPosttitle(event.target.value);
  const handleChangeDesc = (event) => setPostDesc(event.target.value);
  // const newPost = [{ id: 5, title: "episode5", desc: "description5" }];

  posts.push({ title: postTitle, desc: postDesc });

  console.log(postTitle, postDesc);
  return (
    <div className={styles.container}>
      <Head>
        <title>Podcaster</title>
        <meta name="desc" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://nextjs.org">Podcaster!</a>
        </h1>
        <div>
          <h1></h1>
        </div>
        <p className={styles.description}>
          Powered by{" "}
          <code className={styles.code}>
            <a target="blank" href="https://tohidsh.com">
              Tohid Shabanloo
            </a>
          </code>
        </p>
        <div className={styles.inputsContainer}>
          Add Title
          <input className={styles.inputsContainer} onChange={handleChange} />
          <br />
          <br />
          Add Description
          <input
            className={styles.inputsContainer}
            onChange={handleChangeDesc}
          />
        </div>
        <div className={styles.posts}>
          {posts.map((item, i) => (
            <span className={styles.grid} key={item.id}>
              <a href="https://nextjs.org/docs" className={styles.card}>
                <h2>
                  {i + 1}.{item.title} &rarr;
                </h2>
                <h4 className={styles.desc}>{item.desc}</h4>
                {/* <div className={styles.image}>
                  <Image
                    src="/pod.png"
                    alt="Picture of the author"
                    width={1920}
                    height={1080}
                  />
                </div> */}
              </a>
            </span>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
