import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [addtoDb, setAddToDb] = useState([]);
  const [postList, setPostList] = useState([]);
  const [postTitle, setPosttitle] = useState("");
  const [postDesc, setPostDesc] = useState("");

  const dbHandler = () => {
    if (postTitle.length && postDesc.length) {
      setAddToDb({ title: postTitle, desc: postDesc });
    }

    let userData = {
      firstname: firstname.value,
      lastname: lastname.value,
      password: password.value,
    };
  };
  const handleChange = (event) => setPosttitle(event.target.value);
  const handleChangeDesc = (event) => setPostDesc(event.target.value);

  const postAdd = () => {
    if (postTitle.length && postDesc.length) {
      var newPost = { title: postTitle, desc: postDesc };
      setAddToDb({ title: postTitle, desc: postDesc });
      const updatedPost = [...postList, newPost];
      setPostList(updatedPost);
      setPosttitle("");
      setPostDesc("");
    } else {
      alert("All inputs must be filled");
    }
  };
  fetch("https://podcaster00-default-rtdb.firebaseio.com/posts.json", {
    method: "POST",
    headers: {
      "Content-type": "application/json",
    },
    body: JSON.stringify(addtoDb),
  })
    .then((res) => {
      console.log(res);
      clearData();
    })
    .catch((err) => console.log(err));

  console.log(postTitle, postDesc);
  return (
    <div className={styles.container}>
      <Head>
        <title>Podcaster</title>
        <meta name="desc" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a>Podcaster!</a>
        </h1>
        <div>
          <h1></h1>
        </div>

        <div className={styles.inputsContainer}>
          Add Title
          <input
            value={postTitle}
            className={styles.input}
            onChange={handleChange}
          />
          <br />
          <br />
          Add Description
          <input
            value={postDesc}
            className={styles.input}
            onChange={handleChangeDesc}
          />
          <br />
          <button className={styles.button} onClick={postAdd}>
            ADD TO LIST
          </button>
          <br />
          <button className={styles.button} onClick={dbHandler}>
            ADD TO DB
          </button>
        </div>
        <div className={styles.posts}>
          {postList.map((item, i) => (
            <span className={styles.grid} key={item.id}>
              <a href="https://nextjs.org/docs" className={styles.card}>
                <h2>
                  {i + 1}.{item.title} &rarr;
                </h2>
                <h4 className={styles.desc}>{item.desc}</h4>
              </a>
            </span>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <p>
          Powered by{" "}
          <code className={styles.code}>
            <a target="blank" href="https://tohidsh.com">
              Tohid Shabanloo
            </a>
          </code>
        </p>
      </footer>
    </div>
  );
}
